"""Standard-library-only diagnostics for the Aletheia repo."""

from __future__ import annotations

import platform
import sys
from pathlib import Path


PROJECT_ROOT = Path(__file__).resolve().parents[2]


EXPECTED_DIRS = [
    "apps/web",
    "services/api",
    "services/api/app",
    "services/api/app/api/v1/routes",
    "services/api/app/core",
    "services/api/app/db",
    "services/api/app/datasets",
    "services/api/app/cli",
    "services/api/app/text",
    "services/api/app/chunking",
    "services/api/app/ml",
    "services/api/app/evaluation",
    "services/api/app/experiments",
    "services/api/app/replay",
    "services/api/app/search",
    "services/api/app/ingestion",
    "services/api/app/indexing",
    "services/api/app/models",
    "services/api/app/schemas",
    "services/api/alembic",
    "services/api/alembic/versions",
    "services/api/tests",
    "services/worker",
    "infra",
    "data",
    "docs",
    "scripts",
    "tests",
]

EXPECTED_FILES = [
    "README.md",
    "PROJECT_CHARTER.md",
    "AGENTS.md",
    "docs/product-spec.md",
    "docs/dev-commands.md",
    "docs/docs-index.md",
    "docs/architecture.md",
    "docs/retrieval-design.md",
    "docs/evaluation.md",
    "docs/benchmark-results.md",
    "docs/release-readiness.md",
    "docs/repo-audit.md",
    "docs/tradeoffs.md",
    "docs/interview-notes.md",
    "docs/resume-positioning.md",
    "docs/project-one-pager.md",
    "docs/recruiter-notes.md",
    "docs/atlas-integration.md",
    "docs/diagrams/README.md",
    "docs/diagrams/local-live-architecture.md",
    "docs/diagrams/public-snapshot-architecture.md",
    "docs/diagrams/ingestion-indexing-flow.md",
    "docs/diagrams/search-flow.md",
    "docs/diagrams/evaluation-flow.md",
    "docs/diagrams/experiment-comparison-flow.md",
    "docs/diagrams/replay-flow.md",
    "docs/diagrams/deployment-topology.md",
    "docs/diagrams/atlas-integration-flow.md",
    "docs/deployment.md",
    "docs/deploy-vercel.md",
    "docs/deploy-neon.md",
    "docs/deploy-backend.md",
    "docs/ci.md",
    "docs/golden-smoke.md",
    "docs/public-demo-mode.md",
    "docs/public-demo-qa.md",
    "docs/screenshots.md",
    "docs/demo-walkthrough.md",
    "docs/demo-recording-guide.md",
    "docs/runbooks/slow-query.md",
    "docs/runbooks/index-failure.md",
    "docs/runbooks/eval-regression.md",
    ".env.example",
    ".env.production.example",
    ".gitignore",
    ".dockerignore",
    "docker-compose.yml",
    "apps/web/package.json",
    "apps/web/src/app/layout.tsx",
    "apps/web/src/app/page.tsx",
    "apps/web/src/lib/api/client.ts",
    "apps/web/src/lib/api/overview.ts",
    "apps/web/src/lib/api/search.ts",
    "apps/web/src/lib/api/traces.ts",
    "apps/web/src/lib/api/evaluations.ts",
    "apps/web/src/lib/api/experiments.ts",
    "apps/web/src/lib/api/indexes.ts",
    "apps/web/src/lib/api/datasets.ts",
    "apps/web/src/lib/api/replay.ts",
    "apps/web/src/lib/api/system.ts",
    "apps/web/src/lib/api/snapshot.ts",
    "apps/web/src/lib/demo-mode.ts",
    "apps/web/src/lib/format.ts",
    "configs/golden-smoke-thresholds.json",
    "configs/final-benchmark-suite.json",
    "apps/web/src/components/demo/demo-mode-banner.tsx",
    "apps/web/src/components/layout/app-shell.tsx",
    "apps/web/src/components/search/search-lab.tsx",
    "apps/web/src/components/search/search-form.tsx",
    "apps/web/src/components/search/search-results.tsx",
    "apps/web/src/components/search/result-card.tsx",
    "apps/web/src/components/search/score-breakdown.tsx",
    "apps/web/src/components/search/latency-panel.tsx",
    "apps/web/src/components/search/search-metadata-panel.tsx",
    "apps/web/src/components/traces/trace-browser.tsx",
    "apps/web/src/components/traces/trace-filters.tsx",
    "apps/web/src/components/traces/trace-list.tsx",
    "apps/web/src/components/traces/trace-detail.tsx",
    "apps/web/src/components/traces/trace-stage-panel.tsx",
    "apps/web/src/components/traces/trace-candidate-table.tsx",
    "apps/web/src/components/traces/trace-ranking-summary.tsx",
    "apps/web/src/components/traces/trace-json-panel.tsx",
    "apps/web/src/components/traces/rank-movement-panel.tsx",
    "apps/web/src/components/traces/trace-status-badge.tsx",
    "apps/web/src/components/evaluations/evaluation-dashboard.tsx",
    "apps/web/src/components/evaluations/evaluation-run-table.tsx",
    "apps/web/src/components/evaluations/evaluation-run-detail.tsx",
    "apps/web/src/components/evaluations/evaluation-metric-cards.tsx",
    "apps/web/src/components/evaluations/evaluation-metric-chart.tsx",
    "apps/web/src/components/evaluations/evaluation-latency-chart.tsx",
    "apps/web/src/components/evaluations/evaluation-query-results-table.tsx",
    "apps/web/src/components/evaluations/evaluation-report-panel.tsx",
    "apps/web/src/components/evaluations/evaluation-status-badge.tsx",
    "apps/web/src/components/evaluations/metric-value.tsx",
    "apps/web/src/components/experiments/experiment-matrix.tsx",
    "apps/web/src/components/experiments/experiment-config-table.tsx",
    "apps/web/src/components/experiments/experiment-metric-matrix.tsx",
    "apps/web/src/components/experiments/experiment-quality-chart.tsx",
    "apps/web/src/components/experiments/experiment-latency-chart.tsx",
    "apps/web/src/components/experiments/experiment-config-detail.tsx",
    "apps/web/src/components/experiments/experiment-admin-panel.tsx",
    "apps/web/src/components/experiments/experiment-job-status.tsx",
    "apps/web/src/components/experiments/experiment-mode-badge.tsx",
    "apps/web/src/components/experiments/best-metric-badge.tsx",
    "apps/web/src/components/indexes/index-console.tsx",
    "apps/web/src/components/indexes/index-status-cards.tsx",
    "apps/web/src/components/indexes/index-version-table.tsx",
    "apps/web/src/components/indexes/index-version-detail.tsx",
    "apps/web/src/components/indexes/index-health-cards.tsx",
    "apps/web/src/components/indexes/index-job-table.tsx",
    "apps/web/src/components/indexes/index-admin-panel.tsx",
    "apps/web/src/components/indexes/index-job-status.tsx",
    "apps/web/src/components/indexes/index-status-badge.tsx",
    "apps/web/src/components/indexes/index-progress-bar.tsx",
    "apps/web/src/components/datasets/dataset-browser.tsx",
    "apps/web/src/components/datasets/dataset-overview-cards.tsx",
    "apps/web/src/components/datasets/dataset-selector.tsx",
    "apps/web/src/components/datasets/document-table.tsx",
    "apps/web/src/components/datasets/document-detail-panel.tsx",
    "apps/web/src/components/datasets/chunk-table.tsx",
    "apps/web/src/components/datasets/chunk-detail-panel.tsx",
    "apps/web/src/components/datasets/benchmark-query-table.tsx",
    "apps/web/src/components/datasets/benchmark-query-detail-panel.tsx",
    "apps/web/src/components/datasets/relevance-judgment-table.tsx",
    "apps/web/src/components/datasets/dataset-tabs.tsx",
    "apps/web/src/components/datasets/corpus-search-controls.tsx",
    "apps/web/src/components/datasets/metadata-json-panel.tsx",
    "apps/web/src/components/replay/replay-lab.tsx",
    "apps/web/src/components/replay/saved-query-table.tsx",
    "apps/web/src/components/replay/saved-query-detail.tsx",
    "apps/web/src/components/replay/query-replay-table.tsx",
    "apps/web/src/components/replay/query-replay-detail.tsx",
    "apps/web/src/components/replay/replay-metrics-cards.tsx",
    "apps/web/src/components/replay/replay-document-lists.tsx",
    "apps/web/src/components/replay/replay-admin-panel.tsx",
    "apps/web/src/components/replay/replay-job-status.tsx",
    "apps/web/src/components/replay/replay-status-badge.tsx",
    "apps/web/src/components/replay/replay-mode-controls.tsx",
    "apps/web/src/components/replay/replay-json-panel.tsx",
    "apps/web/src/components/system/system-health-dashboard.tsx",
    "apps/web/src/components/system/service-health-card.tsx",
    "apps/web/src/components/system/system-health-grid.tsx",
    "apps/web/src/components/system/worker-heartbeat-panel.tsx",
    "apps/web/src/components/system/queue-status-panel.tsx",
    "apps/web/src/components/system/model-status-panel.tsx",
    "apps/web/src/components/system/system-events-table.tsx",
    "apps/web/src/components/system/system-event-severity-badge.tsx",
    "apps/web/src/components/system/system-refresh-bar.tsx",
    "apps/web/src/components/system/operational-status-badge.tsx",
    "apps/web/src/app/search/page.tsx",
    "apps/web/src/app/traces/page.tsx",
    "apps/web/src/app/evaluations/page.tsx",
    "apps/web/src/app/experiments/page.tsx",
    "apps/web/src/app/indexes/page.tsx",
    "apps/web/src/app/replay/page.tsx",
    "apps/web/src/app/datasets/page.tsx",
    "apps/web/src/app/system/page.tsx",
    "services/api/Dockerfile",
    "services/api/Dockerfile.worker",
    "services/api/pyproject.toml",
    "services/api/alembic.ini",
    "services/api/alembic/env.py",
    "services/api/alembic/script.py.mako",
    "services/api/alembic/versions/0001_initialize_database.py",
    "services/api/alembic/versions/0002_create_core_schema.py",
    "services/api/app/main.py",
    "services/api/app/api/v1/router.py",
    "services/api/app/api/v1/routes/health.py",
    "services/api/app/core/config.py",
    "services/api/app/core/app_mode.py",
    "services/api/app/core/logging.py",
    "services/api/app/core/middleware.py",
    "services/api/app/core/redis.py",
    "services/api/app/db/base.py",
    "services/api/app/db/session.py",
    "services/api/app/db/health.py",
    "services/api/app/models/__init__.py",
    "services/api/app/models/mixins.py",
    "services/api/app/models/datasets.py",
    "services/api/app/models/indexing.py",
    "services/api/app/models/queries.py",
    "services/api/app/models/experiments.py",
    "services/api/app/models/evaluation.py",
    "services/api/app/models/system.py",
    "services/api/app/jobs/__init__.py",
    "services/api/app/jobs/health.py",
    "services/api/app/jobs/queue.py",
    "services/api/app/worker/__init__.py",
    "services/api/app/worker/runner.py",
    "services/api/app/worker/heartbeat.py",
    "services/api/app/datasets/__init__.py",
    "services/api/app/datasets/scifact.py",
    "services/api/app/cli/__init__.py",
    "services/api/app/cli/load_scifact.py",
    "services/api/app/cli/chunk_documents.py",
    "services/api/app/text/__init__.py",
    "services/api/app/text/normalization.py",
    "services/api/app/text/chunking.py",
    "services/api/app/text/hashing.py",
    "services/api/app/chunking/__init__.py",
    "services/api/app/chunking/service.py",
    "services/api/app/ml/__init__.py",
    "services/api/app/ml/embeddings.py",
    "services/api/app/ml/reranker.py",
    "services/api/app/evaluation/__init__.py",
    "services/api/app/evaluation/metrics.py",
    "services/api/app/evaluation/latency.py",
    "services/api/app/evaluation/correctness.py",
    "services/api/app/evaluation/runner.py",
    "services/api/app/evaluation/smoke.py",
    "services/api/app/evaluation/reporting.py",
    "services/api/app/evaluation/jobs.py",
    "services/api/app/benchmarks/__init__.py",
    "services/api/app/benchmarks/suite.py",
    "services/api/app/benchmarks/reporting.py",
    "services/api/app/experiments/__init__.py",
    "services/api/app/experiments/defaults.py",
    "services/api/app/experiments/service.py",
    "services/api/app/experiments/comparison.py",
    "services/api/app/experiments/reporting.py",
    "services/api/app/experiments/jobs.py",
    "services/api/app/replay/__init__.py",
    "services/api/app/replay/golden.py",
    "services/api/app/replay/service.py",
    "services/api/app/replay/comparison.py",
    "services/api/app/replay/reporting.py",
    "services/api/app/replay/jobs.py",
    "services/api/app/search/__init__.py",
    "services/api/app/search/opensearch_client.py",
    "services/api/app/search/qdrant_client.py",
    "services/api/app/search/lexical_mapping.py",
    "services/api/app/search/lexical_indexer.py",
    "services/api/app/search/vector_indexer.py",
    "services/api/app/search/retrieval_models.py",
    "services/api/app/search/fusion.py",
    "services/api/app/search/lexical_retriever.py",
    "services/api/app/search/dense_retriever.py",
    "services/api/app/search/hybrid_retriever.py",
    "services/api/app/search/reranker.py",
    "services/api/app/search/tracing.py",
    "services/api/app/search/trace_service.py",
    "services/api/app/search/service.py",
    "services/api/app/ingestion/__init__.py",
    "services/api/app/ingestion/statuses.py",
    "services/api/app/ingestion/service.py",
    "services/api/app/ingestion/jobs.py",
    "services/api/app/indexing/__init__.py",
    "services/api/app/indexing/statuses.py",
    "services/api/app/indexing/service.py",
    "services/api/app/indexing/jobs.py",
    "services/api/app/cli/build_lexical_index.py",
    "services/api/app/cli/build_vector_index.py",
    "services/api/app/cli/search_bm25.py",
    "services/api/app/cli/search_dense.py",
    "services/api/app/cli/search_hybrid.py",
    "services/api/app/cli/search_hybrid_rerank.py",
    "services/api/app/cli/inspect_trace.py",
    "services/api/app/cli/evaluate_metrics_fixture.py",
    "services/api/app/cli/check_eval_alignment.py",
    "services/api/app/cli/evaluate_trace.py",
    "services/api/app/cli/run_evaluation.py",
    "services/api/app/cli/run_benchmark_suite.py",
    "services/api/app/cli/run_golden_smoke.py",
    "services/api/app/cli/seed_experiment_configs.py",
    "services/api/app/cli/run_comparison.py",
    "services/api/app/cli/seed_golden_queries.py",
    "services/api/app/cli/replay_saved_query.py",
    "services/api/app/cli/run_golden_replay.py",
    "services/api/app/cli/embed_text.py",
    "services/api/app/cli/export_demo_snapshot.py",
    "services/api/app/export/__init__.py",
    "services/api/app/export/demo_snapshot.py",
    "services/api/app/api/dependencies/__init__.py",
    "services/api/app/api/dependencies/admin.py",
    "services/api/app/api/v1/routes/admin.py",
    "services/api/app/api/v1/routes/datasets.py",
    "services/api/app/api/v1/routes/evaluations.py",
    "services/api/app/api/v1/routes/experiments.py",
    "services/api/app/api/v1/routes/replay.py",
    "services/api/app/api/v1/routes/indexes.py",
    "services/api/app/api/v1/routes/ingestion.py",
    "services/api/app/api/v1/routes/search.py",
    "services/api/app/api/v1/routes/system.py",
    "services/api/app/schemas/admin.py",
    "services/api/app/schemas/datasets.py",
    "services/api/app/schemas/evaluations.py",
    "services/api/app/schemas/experiments.py",
    "services/api/app/schemas/replay.py",
    "services/api/app/schemas/ingestion.py",
    "services/api/app/schemas/indexes.py",
    "services/api/app/schemas/search.py",
    "services/api/app/schemas/health.py",
    "services/api/app/schemas/system.py",
    "services/api/tests/test_health.py",
    "services/api/tests/test_db_health.py",
    "services/api/tests/test_model_metadata.py",
    "services/api/tests/test_jobs.py",
    "services/api/tests/test_system_routes.py",
    "services/api/tests/test_admin_auth.py",
    "services/api/tests/test_scifact_loader.py",
    "services/api/tests/test_dataset_routes.py",
    "services/api/tests/test_text_processing.py",
    "services/api/tests/test_chunking_service.py",
    "services/api/tests/test_ingestion_service.py",
    "services/api/tests/test_ingestion_routes.py",
    "services/api/tests/test_indexing_statuses.py",
    "services/api/tests/test_indexing_service.py",
    "services/api/tests/test_index_routes.py",
    "scripts/powershell/db-upgrade.ps1",
    "scripts/powershell/db-downgrade.ps1",
    "scripts/powershell/db-current.ps1",
    "scripts/powershell/db-history.ps1",
    "scripts/powershell/ingest-scifact.ps1",
    "scripts/powershell/chunk-documents.ps1",
    "scripts/powershell/start-scifact-ingestion-job.ps1",
    "scripts/powershell/create-index-version.ps1",
    "scripts/powershell/index-status.ps1",
    "scripts/powershell/activate-index-version.ps1",
    "scripts/powershell/build-lexical-index.ps1",
    "scripts/powershell/start-lexical-index-build-job.ps1",
    "scripts/powershell/build-vector-index.ps1",
    "scripts/powershell/start-vector-index-build-job.ps1",
    "scripts/powershell/search-bm25.ps1",
    "scripts/powershell/search-dense.ps1",
    "scripts/powershell/search-hybrid.ps1",
    "scripts/powershell/search-hybrid-rerank.ps1",
    "scripts/powershell/inspect-trace.ps1",
    "scripts/powershell/list-traces.ps1",
    "scripts/powershell/evaluate-metrics-fixture.ps1",
    "scripts/powershell/check-eval-alignment.ps1",
    "scripts/powershell/evaluate-trace.ps1",
    "scripts/powershell/run-evaluation.ps1",
    "scripts/powershell/run-eval.ps1",
    "scripts/powershell/start-evaluation-job.ps1",
    "scripts/powershell/list-evaluation-runs.ps1",
    "scripts/powershell/show-evaluation-run.ps1",
    "scripts/powershell/seed-experiment-configs.ps1",
    "scripts/powershell/list-experiment-configs.ps1",
    "scripts/powershell/run-comparison.ps1",
    "scripts/powershell/start-comparison-job.ps1",
    "scripts/powershell/seed-golden-queries.ps1",
    "scripts/powershell/list-saved-queries.ps1",
    "scripts/powershell/replay-saved-query.ps1",
    "scripts/powershell/run-golden-replay.ps1",
    "scripts/powershell/start-golden-replay-job.ps1",
    "scripts/powershell/list-query-replays.ps1",
    "scripts/powershell/show-query-replay.ps1",
    "scripts/powershell/web.ps1",
    "scripts/powershell/web-build.ps1",
    "scripts/powershell/web-lint.ps1",
    "scripts/powershell/search-api.ps1",
    "scripts/powershell/embed-text.ps1",
    "scripts/powershell/worker.ps1",
    "scripts/powershell/enqueue-test-job.ps1",
    "scripts/powershell/admin-status.ps1",
    "scripts/powershell/ci-check.ps1",
    "scripts/powershell/run-golden-smoke.ps1",
    "scripts/powershell/run-final-benchmark-suite.ps1",
    "scripts/powershell/repo-audit.ps1",
    "scripts/powershell/production-build-check.ps1",
    "scripts/powershell/docker-build-api.ps1",
    "scripts/powershell/docker-build-worker.ps1",
    "scripts/powershell/export-demo-snapshot.ps1",
    "apps/web/public/demo-data/.gitkeep",
    "apps/web/public/demo-data/manifest.json",
    ".github/workflows/ci.yml",
    "data/samples/metrics-fixture.json",
    "reports/evaluations/.gitkeep",
    "reports/smoke/.gitkeep",
    "reports/benchmarks/.gitkeep",
    "reports/benchmarks/README.md",
    "docs/assets/screenshots/.gitkeep",
    "docs/assets/video/.gitkeep",
    "docs/assets/screenshots/overview.png",
    "docs/assets/screenshots/search-lab.png",
    "docs/assets/screenshots/query-trace.png",
    "docs/assets/screenshots/evaluation-dashboard.png",
    "docs/assets/screenshots/experiment-matrix.png",
    "docs/assets/screenshots/index-console.png",
    "docs/assets/screenshots/dataset-browser.png",
    "docs/assets/screenshots/replay-lab.png",
    "docs/assets/screenshots/system-health.png",
    "reports/evaluations/comparisons/.gitkeep",
    "reports/replays/.gitkeep",
]


def status_line(status: str, label: str, detail: str = "") -> None:
    if detail:
        print(f"{status:<4} {label:<55} {detail}")
    else:
        print(f"{status:<4} {label}")


def check_path(path_text: str, should_be_dir: bool) -> bool:
    path = PROJECT_ROOT / path_text

    if should_be_dir:
        exists = path.is_dir()
        kind = "directory"
    else:
        exists = path.is_file()
        kind = "file"

    if exists:
        status_line("PASS", path_text, f"{kind} exists")
        return True

    status_line("WARN", path_text, f"missing expected {kind}")
    return False


def main() -> int:
    print()
    print("Aletheia doctor")
    print("================")
    print(f"Project root: {PROJECT_ROOT}")
    print(f"Python: {sys.version.split()[0]}")
    print(f"Python executable: {sys.executable}")
    print(f"Platform: {platform.platform()}")
    print()

    print("Expected folders")
    print("----------------")
    dir_results = [check_path(path, should_be_dir=True) for path in EXPECTED_DIRS]

    print()
    print("Expected files")
    print("--------------")
    file_results = [check_path(path, should_be_dir=False) for path in EXPECTED_FILES]

    print()
    if all(dir_results) and all(file_results):
        print("PASS Aletheia repo structure looks ready for the current step.")
        return 0

    print("WARN Aletheia repo structure has missing expected items.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
