from __future__ import annotations

import json
from dataclasses import dataclass
from datetime import date, datetime, timezone
from decimal import Decimal
from enum import Enum
from pathlib import Path
from typing import Any
from uuid import UUID

from sqlalchemy import Select, func, select
from sqlalchemy.orm import Session

from app.models.datasets import BenchmarkQuery, Chunk, Dataset, Document, RelevanceJudgment
from app.models.evaluation import EvaluationQueryResult, EvaluationReport, EvaluationRun
from app.models.experiments import ExperimentConfig
from app.models.indexing import IndexJob, IndexVersion
from app.models.queries import Query, QueryReplay, QueryTrace, RetrievalCandidate, SavedQuery
from app.models.system import SystemEvent


SNAPSHOT_FILES = [
    "manifest.json",
    "overview.json",
    "index-status.json",
    "datasets.json",
    "documents-sample.json",
    "chunks-sample.json",
    "benchmark-queries-sample.json",
    "relevance-judgments-sample.json",
    "search-scenarios.json",
    "traces.json",
    "evaluations.json",
    "experiments.json",
    "replay.json",
    "system.json",
]

TEXT_PREVIEW_CHARS = 500


@dataclass(frozen=True)
class SnapshotLimits:
    scenario_limit: int = 4
    trace_limit: int = 20
    evaluation_limit: int = 20
    document_limit: int = 20
    chunk_limit: int = 20
    query_limit: int = 20
    qrel_limit: int = 20
    replay_limit: int = 20
    include_large_text: bool = False


def json_safe(value: Any) -> Any:
    if isinstance(value, UUID):
        return str(value)
    if isinstance(value, datetime):
        return value.astimezone(timezone.utc).isoformat()
    if isinstance(value, date):
        return value.isoformat()
    if isinstance(value, Decimal):
        return float(value)
    if isinstance(value, Enum):
        return value.value
    if isinstance(value, dict):
        return {str(key): json_safe(nested) for key, nested in value.items()}
    if isinstance(value, (list, tuple, set)):
        return [json_safe(item) for item in value]
    return value


def truncate_text(value: str | None, include_large_text: bool, max_chars: int = TEXT_PREVIEW_CHARS) -> str | None:
    if value is None or include_large_text or len(value) <= max_chars:
        return value
    return f"{value[:max_chars]}..."


def row_to_dict(row: Any, fields: list[str], include_large_text: bool = False) -> dict[str, Any]:
    item: dict[str, Any] = {}
    for field in fields:
        value = getattr(row, field)
        if field == "text":
            value = truncate_text(value, include_large_text)
        item[field] = json_safe(value)
    return item


def write_json(output_dir: Path, file_name: str, payload: dict[str, Any] | list[Any]) -> None:
    output_dir.mkdir(parents=True, exist_ok=True)
    target = output_dir / file_name
    temp = target.with_suffix(f"{target.suffix}.tmp")
    temp.write_text(
        json.dumps(json_safe(payload), indent=2, sort_keys=True) + "\n",
        encoding="utf-8",
    )
    temp.replace(target)


def build_manifest(
    *,
    counts: dict[str, int],
    warnings: list[str],
    generated_at: datetime | None = None,
    files: list[str] | None = None,
) -> dict[str, Any]:
    return {
        "generated": True,
        "generated_at": json_safe(generated_at or datetime.now(timezone.utc)),
        "source": "local_full_stack_export",
        "project": "Aletheia",
        "demo_mode": "snapshot",
        "explanation": (
            "Real precomputed outputs generated by the full local Aletheia pipeline. "
            "Live public retrieval and admin jobs are disabled to avoid always-on "
            "infrastructure costs."
        ),
        "counts": counts,
        "files": files or SNAPSHOT_FILES,
        "warnings": warnings,
    }


def limited(statement: Select[tuple[Any]], limit: int) -> Select[tuple[Any]]:
    return statement.limit(max(0, limit))


def count_rows(db: Session, model: Any) -> int:
    return int(db.scalar(select(func.count(model.id))) or 0)


def latest_rows(db: Session, model: Any, limit: int, order_field: str = "created_at") -> list[Any]:
    field = getattr(model, order_field)
    return list(db.scalars(select(model).order_by(field.desc()).limit(max(0, limit))).all())


def dataset_summary(db: Session, dataset: Dataset) -> dict[str, Any]:
    dataset_id = dataset.id
    return {
        **row_to_dict(
            dataset,
            [
                "id",
                "name",
                "source",
                "version",
                "description",
                "license_name",
                "license_url",
                "source_url",
                "metadata_json",
                "created_at",
                "updated_at",
            ],
        ),
        "document_count": int(
            db.scalar(select(func.count(Document.id)).where(Document.dataset_id == dataset_id)) or 0
        ),
        "chunk_count": int(db.scalar(select(func.count(Chunk.id)).where(Chunk.dataset_id == dataset_id)) or 0),
        "benchmark_query_count": int(
            db.scalar(select(func.count(BenchmarkQuery.id)).where(BenchmarkQuery.dataset_id == dataset_id)) or 0
        ),
        "relevance_judgment_count": int(
            db.scalar(select(func.count(RelevanceJudgment.id)).where(RelevanceJudgment.dataset_id == dataset_id)) or 0
        ),
    }


def index_version_item(row: IndexVersion) -> dict[str, Any]:
    return row_to_dict(
        row,
        [
            "id",
            "dataset_id",
            "name",
            "status",
            "is_active",
            "lexical_index_name",
            "vector_collection_name",
            "embedding_model",
            "embedding_dimension",
            "chunking_strategy",
            "chunking_version",
            "document_count",
            "chunk_count",
            "vector_count",
            "config_json",
            "notes",
            "created_at",
            "activated_at",
            "updated_at",
        ],
    )


def index_job_item(row: IndexJob) -> dict[str, Any]:
    return row_to_dict(
        row,
        [
            "id",
            "index_version_id",
            "job_id",
            "job_type",
            "status",
            "started_at",
            "completed_at",
            "chunks_total",
            "chunks_completed",
            "chunks_failed",
            "error_message",
            "config_json",
            "created_at",
            "updated_at",
        ],
    )


def evaluation_run_item(row: EvaluationRun) -> dict[str, Any]:
    return row_to_dict(
        row,
        [
            "id",
            "name",
            "dataset_id",
            "index_version_id",
            "experiment_config_id",
            "status",
            "started_at",
            "completed_at",
            "query_count",
            "failed_query_count",
            "recall_at_5",
            "recall_at_10",
            "mrr_at_10",
            "ndcg_at_10",
            "p50_latency_ms",
            "p95_latency_ms",
            "avg_latency_ms",
            "config_json",
            "notes",
            "report_path",
            "created_at",
            "updated_at",
        ],
    )


def evaluation_result_item(row: EvaluationQueryResult) -> dict[str, Any]:
    return row_to_dict(
        row,
        [
            "id",
            "evaluation_run_id",
            "benchmark_query_id",
            "query_external_id",
            "query_text",
            "relevant_document_ids_json",
            "retrieved_document_ids_json",
            "recall_at_5",
            "recall_at_10",
            "mrr_at_10",
            "ndcg_at_10",
            "latency_ms",
            "trace_id",
            "error_message",
            "created_at",
        ],
    )


def experiment_config_item(row: ExperimentConfig) -> dict[str, Any]:
    return row_to_dict(
        row,
        [
            "id",
            "name",
            "retrieval_mode",
            "bm25_candidate_k",
            "dense_candidate_k",
            "hybrid_candidate_k",
            "rerank_top_n",
            "top_k_final",
            "fusion_method",
            "fusion_params_json",
            "embedding_model",
            "reranker_model",
            "config_json",
            "is_default",
            "created_at",
            "updated_at",
        ],
    )


def candidate_item(row: RetrievalCandidate) -> dict[str, Any]:
    return row_to_dict(
        row,
        [
            "id",
            "query_id",
            "trace_id",
            "chunk_id",
            "document_id",
            "source",
            "bm25_rank",
            "dense_rank",
            "fusion_rank",
            "rerank_rank",
            "final_rank",
            "bm25_score",
            "dense_score",
            "fusion_score",
            "reranker_score",
            "latency_ms",
            "metadata_json",
            "created_at",
        ],
    )


def query_item(row: Query) -> dict[str, Any]:
    return row_to_dict(
        row,
        [
            "id",
            "text",
            "retrieval_mode",
            "index_version_id",
            "request_id",
            "total_latency_ms",
            "status",
            "error_message",
            "metadata_json",
            "created_at",
        ],
    )


def trace_detail(db: Session, trace: QueryTrace, query: Query | None = None) -> dict[str, Any]:
    query_row = query or db.get(Query, trace.query_id)
    candidates = list(
        db.scalars(
            select(RetrievalCandidate)
            .where(RetrievalCandidate.trace_id == trace.id)
            .order_by(RetrievalCandidate.source.asc(), RetrievalCandidate.final_rank.asc().nullslast())
        ).all()
    )
    candidate_items = [candidate_item(candidate) for candidate in candidates]
    candidates_by_source: dict[str, list[dict[str, Any]]] = {}
    for item in candidate_items:
        source = str(item.get("source") or "unknown")
        candidates_by_source.setdefault(source, []).append(item)

    return {
        "trace_id": json_safe(trace.id),
        "query_id": json_safe(trace.query_id),
        "created_at": json_safe(trace.created_at),
        "query": query_item(query_row) if query_row else None,
        "trace_json": json_safe(trace.trace_json),
        "candidates": candidate_items,
        "candidates_by_source": candidates_by_source,
    }


def scenario_from_trace(db: Session, trace: QueryTrace, query: Query) -> dict[str, Any]:
    final_candidates = list(
        db.scalars(
            select(RetrievalCandidate)
            .where(RetrievalCandidate.trace_id == trace.id)
            .order_by(RetrievalCandidate.final_rank.asc().nullslast())
            .limit(10)
        ).all()
    )
    results: list[dict[str, Any]] = []
    for candidate in final_candidates:
        chunk = db.get(Chunk, candidate.chunk_id) if candidate.chunk_id else None
        document = db.get(Document, candidate.document_id) if candidate.document_id else None
        results.append(
            {
                "rank": candidate.final_rank,
                "chunk_id": json_safe(candidate.chunk_id),
                "document_id": json_safe(candidate.document_id),
                "title": document.title if document else None,
                "document_external_id": document.external_id if document else None,
                "chunk_external_id": chunk.external_id if chunk else None,
                "text": truncate_text(chunk.text if chunk else None, include_large_text=False),
                "score": candidate.reranker_score
                if candidate.reranker_score is not None
                else candidate.fusion_score
                if candidate.fusion_score is not None
                else candidate.dense_score
                if candidate.dense_score is not None
                else candidate.bm25_score,
                "score_breakdown": {
                    "bm25_score": candidate.bm25_score,
                    "dense_score": candidate.dense_score,
                    "fusion_score": candidate.fusion_score,
                    "reranker_score": candidate.reranker_score,
                    "bm25_rank": candidate.bm25_rank,
                    "dense_rank": candidate.dense_rank,
                    "fusion_rank": candidate.fusion_rank,
                    "rerank_rank": candidate.rerank_rank,
                },
                "token_count": chunk.token_count if chunk else None,
                "chunking_strategy": chunk.chunking_strategy if chunk else None,
                "chunking_version": chunk.chunking_version if chunk else None,
                "metadata_json": candidate.metadata_json,
            }
        )

    return {
        "scenario_id": f"{query.retrieval_mode}_{trace.id}",
        "label": f"{query.retrieval_mode} trace",
        "query": query.text,
        "retrieval_mode": query.retrieval_mode,
        "trace_id": json_safe(trace.id),
        "query_id": json_safe(query.id),
        "result_count": len(results),
        "results": json_safe(results),
        "latency_ms": query.total_latency_ms,
        "search_response": {
            "query_id": json_safe(query.id),
            "trace_id": json_safe(trace.id),
            "query": query.text,
            "retrieval_mode": query.retrieval_mode,
            "result_count": len(results),
            "results": json_safe(results),
            "latency_ms": query.total_latency_ms,
        },
        "explanation": (
            "Real precomputed retrieval output exported from a stored query trace. "
            "No live hosted retrieval is run for this scenario."
        ),
    }


def export_demo_snapshot(db: Session, output_dir: Path, limits: SnapshotLimits) -> dict[str, Any]:
    warnings: list[str] = []
    output_dir.mkdir(parents=True, exist_ok=True)

    counts = {
        "datasets": count_rows(db, Dataset),
        "documents": count_rows(db, Document),
        "chunks": count_rows(db, Chunk),
        "benchmark_queries": count_rows(db, BenchmarkQuery),
        "relevance_judgments": count_rows(db, RelevanceJudgment),
        "index_versions": count_rows(db, IndexVersion),
        "evaluation_runs": count_rows(db, EvaluationRun),
        "traces": count_rows(db, QueryTrace),
        "saved_queries": count_rows(db, SavedQuery),
        "query_replays": count_rows(db, QueryReplay),
    }

    datasets = [dataset_summary(db, dataset) for dataset in latest_rows(db, Dataset, 50)]
    documents = [
        row_to_dict(
            row,
            [
                "id",
                "dataset_id",
                "external_id",
                "title",
                "text",
                "source_url",
                "metadata_json",
                "created_at",
                "updated_at",
            ],
            include_large_text=limits.include_large_text,
        )
        for row in latest_rows(db, Document, limits.document_limit)
    ]
    chunks = [
        row_to_dict(
            row,
            [
                "id",
                "dataset_id",
                "document_id",
                "external_id",
                "chunk_index",
                "text",
                "token_count",
                "char_start",
                "char_end",
                "content_hash",
                "chunking_strategy",
                "chunking_version",
                "metadata_json",
                "created_at",
            ],
            include_large_text=limits.include_large_text,
        )
        for row in latest_rows(db, Chunk, limits.chunk_limit)
    ]
    benchmark_queries = [
        row_to_dict(row, ["id", "dataset_id", "external_id", "text", "split", "metadata_json", "created_at"])
        for row in latest_rows(db, BenchmarkQuery, limits.query_limit)
    ]
    qrels = [
        row_to_dict(
            row,
            [
                "id",
                "dataset_id",
                "query_id",
                "document_id",
                "query_external_id",
                "document_external_id",
                "relevance_score",
                "metadata_json",
                "created_at",
            ],
        )
        for row in latest_rows(db, RelevanceJudgment, limits.qrel_limit)
    ]

    active_index = db.scalar(select(IndexVersion).where(IndexVersion.is_active.is_(True)).limit(1))
    latest_index_versions = [index_version_item(row) for row in latest_rows(db, IndexVersion, 20)]
    latest_index_jobs = [index_job_item(row) for row in latest_rows(db, IndexJob, 20)]

    trace_pairs = list(
        db.execute(
            select(QueryTrace, Query)
            .join(Query, QueryTrace.query_id == Query.id)
            .order_by(QueryTrace.created_at.desc())
            .limit(max(limits.trace_limit, limits.scenario_limit * 4))
        ).all()
    )
    traces = [trace_detail(db, trace, query) for trace, query in trace_pairs[: limits.trace_limit]]

    scenarios: list[dict[str, Any]] = []
    seen_modes: set[str] = set()
    for trace, query in trace_pairs:
        if query.retrieval_mode in seen_modes:
            continue
        scenarios.append(scenario_from_trace(db, trace, query))
        seen_modes.add(query.retrieval_mode)
        if len(scenarios) >= limits.scenario_limit:
            break

    expected_modes = {"bm25", "dense", "hybrid", "hybrid_rerank"}
    missing_modes = sorted(expected_modes - seen_modes)
    if missing_modes:
        warnings.append(
            "No stored query traces were available for retrieval modes: " + ", ".join(missing_modes)
        )

    evaluation_runs = latest_rows(db, EvaluationRun, limits.evaluation_limit)
    evaluation_ids = [row.id for row in evaluation_runs]
    evaluation_results = []
    if evaluation_ids:
        evaluation_results = [
            evaluation_result_item(row)
            for row in db.scalars(
                select(EvaluationQueryResult)
                .where(EvaluationQueryResult.evaluation_run_id.in_(evaluation_ids))
                .order_by(EvaluationQueryResult.created_at.desc())
                .limit(limits.evaluation_limit * 5)
            ).all()
        ]
    evaluation_reports = [
        row_to_dict(row, ["id", "evaluation_run_id", "report_format", "report_path", "summary_json", "created_at"])
        for row in db.scalars(
            select(EvaluationReport).order_by(EvaluationReport.created_at.desc()).limit(limits.evaluation_limit)
        ).all()
    ]

    experiment_configs = [experiment_config_item(row) for row in latest_rows(db, ExperimentConfig, 100)]
    latest_evaluation_by_config: dict[str, dict[str, Any]] = {}
    for run in evaluation_runs:
        if run.experiment_config_id and str(run.experiment_config_id) not in latest_evaluation_by_config:
            latest_evaluation_by_config[str(run.experiment_config_id)] = evaluation_run_item(run)

    saved_queries = [
        row_to_dict(row, ["id", "dataset_id", "name", "text", "source", "metadata_json", "created_at", "updated_at"])
        for row in latest_rows(db, SavedQuery, limits.query_limit)
    ]
    query_replays = [
        row_to_dict(
            row,
            [
                "id",
                "saved_query_id",
                "original_query_id",
                "source_trace_id",
                "target_trace_id",
                "experiment_config_id",
                "index_version_id",
                "status",
                "comparison_json",
                "error_message",
                "started_at",
                "completed_at",
                "created_at",
                "updated_at",
            ],
        )
        for row in latest_rows(db, QueryReplay, limits.replay_limit)
    ]
    system_events = [
        row_to_dict(
            row,
            [
                "id",
                "event_type",
                "severity",
                "message",
                "request_id",
                "job_id",
                "trace_id",
                "metadata_json",
                "created_at",
            ],
        )
        for row in latest_rows(db, SystemEvent, 50)
    ]

    index_status = {
        "active_index_version": index_version_item(active_index) if active_index else None,
        "latest_index_versions": latest_index_versions,
        "latest_index_jobs": latest_index_jobs,
        "dataset_count": counts["datasets"],
        "index_version_count": counts["index_versions"],
        "ready_index_version_count": int(
            db.scalar(select(func.count(IndexVersion.id)).where(IndexVersion.status == "ready")) or 0
        ),
        "active_index_version_count": int(
            db.scalar(select(func.count(IndexVersion.id)).where(IndexVersion.is_active.is_(True))) or 0
        ),
    }

    overview = {
        "mode": "snapshot",
        "explanation": (
            "This hosted demo uses real precomputed outputs generated by the full local Aletheia pipeline. "
            "Live retrieval, index rebuilds, and admin jobs are disabled publicly to avoid always-on search "
            "and ML infrastructure costs."
        ),
        "active_index": index_status["active_index_version"],
        "datasets": datasets,
        "latest_evaluations": [evaluation_run_item(row) for row in evaluation_runs[:5]],
        "experiment_configs": experiment_configs[:8],
        "recent_traces": [
            {
                "trace_id": item["trace_id"],
                "query_id": item["query_id"],
                "query_text": item["query"]["text"] if item.get("query") else None,
                "retrieval_mode": item["query"]["retrieval_mode"] if item.get("query") else None,
                "status": item["query"]["status"] if item.get("query") else None,
                "total_latency_ms": item["query"]["total_latency_ms"] if item.get("query") else None,
                "created_at": item["created_at"],
            }
            for item in traces[:5]
        ],
        "saved_query_count": counts["saved_queries"],
        "query_replay_count": counts["query_replays"],
        "system_events": system_events[:5],
        "counts": counts,
    }

    system = {
        "mode": "snapshot",
        "backend_live": False,
        "live_admin_actions_enabled": False,
        "explanation": (
            "Public snapshot mode serves real exported outputs from the local full stack. "
            "It does not claim live hosted infrastructure health."
        ),
        "local_full_stack_components": [
            "FastAPI",
            "Postgres",
            "Redis/RQ",
            "OpenSearch",
            "Qdrant",
            "embedding model",
            "reranker",
        ],
        "public_hosted_components": ["Vercel frontend", "Neon schema", "static snapshot data"],
        "system_events": system_events,
    }

    payloads: dict[str, dict[str, Any]] = {
        "overview.json": overview,
        "index-status.json": index_status,
        "datasets.json": {
            "datasets": datasets,
            "document_samples": documents,
            "chunk_samples": chunks,
            "benchmark_query_samples": benchmark_queries,
            "relevance_judgment_samples": qrels,
        },
        "documents-sample.json": {"total": counts["documents"], "items": documents},
        "chunks-sample.json": {"total": counts["chunks"], "items": chunks},
        "benchmark-queries-sample.json": {"total": counts["benchmark_queries"], "items": benchmark_queries},
        "relevance-judgments-sample.json": {"total": counts["relevance_judgments"], "items": qrels},
        "search-scenarios.json": {"items": scenarios, "warnings": warnings},
        "traces.json": {"total": counts["traces"], "items": traces},
        "evaluations.json": {
            "runs": [evaluation_run_item(row) for row in evaluation_runs],
            "query_results": evaluation_results,
            "reports": evaluation_reports,
        },
        "experiments.json": {
            "configs": experiment_configs,
            "latest_evaluation_by_config": latest_evaluation_by_config,
        },
        "replay.json": {
            "saved_queries": saved_queries,
            "query_replays": query_replays,
        },
        "system.json": system,
    }

    for file_name, payload in payloads.items():
        write_json(output_dir, file_name, payload)

    manifest = build_manifest(counts=counts, warnings=warnings, files=SNAPSHOT_FILES)
    write_json(output_dir, "manifest.json", manifest)
    return manifest
