PENDING = "pending"
BUILDING = "building"
READY = "ready"
ACTIVE = "active"
FAILED = "failed"
DEPRECATED = "deprecated"

BUILDABLE_STATUSES = {PENDING}
ACTIVATABLE_STATUSES = {READY}
TERMINAL_STATUSES = {FAILED, DEPRECATED}
NON_ACTIVE_STATUSES = {PENDING, BUILDING, READY, FAILED, DEPRECATED}
