"""create_core_schema

Revision ID: 0002_create_core_schema
Revises: 0001_initialize_database
Create Date: 2026-04-25 15:50:18.555946

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa

from sqlalchemy.dialects import postgresql

revision: str = "0002_create_core_schema"
down_revision: str | None = "0001_initialize_database"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('datasets',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('source', sa.String(), nullable=True),
    sa.Column('version', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('license_name', sa.String(), nullable=True),
    sa.Column('license_url', sa.String(), nullable=True),
    sa.Column('source_url', sa.String(), nullable=True),
    sa.Column('metadata_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_datasets')),
    sa.UniqueConstraint('name', 'version', name=op.f('uq_datasets_name'))
    )
    op.create_index('ix_datasets_name', 'datasets', ['name'], unique=False)
    op.create_index('ix_datasets_source', 'datasets', ['source'], unique=False)
    op.create_table('experiment_configs',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('retrieval_mode', sa.String(), nullable=False),
    sa.Column('bm25_candidate_k', sa.Integer(), nullable=False),
    sa.Column('dense_candidate_k', sa.Integer(), nullable=False),
    sa.Column('hybrid_candidate_k', sa.Integer(), nullable=False),
    sa.Column('rerank_top_n', sa.Integer(), nullable=False),
    sa.Column('top_k_final', sa.Integer(), nullable=False),
    sa.Column('fusion_method', sa.String(), nullable=True),
    sa.Column('fusion_params_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('embedding_model', sa.String(), nullable=True),
    sa.Column('reranker_model', sa.String(), nullable=True),
    sa.Column('config_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_experiment_configs')),
    sa.UniqueConstraint('name', name=op.f('uq_experiment_configs_name'))
    )
    op.create_index('ix_experiment_configs_is_default', 'experiment_configs', ['is_default'], unique=False)
    op.create_index('ix_experiment_configs_retrieval_mode', 'experiment_configs', ['retrieval_mode'], unique=False)
    op.create_table('system_events',
    sa.Column('event_type', sa.String(), nullable=False),
    sa.Column('severity', sa.String(), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('request_id', sa.String(), nullable=True),
    sa.Column('job_id', sa.String(), nullable=True),
    sa.Column('trace_id', sa.UUID(), nullable=True),
    sa.Column('metadata_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_system_events'))
    )
    op.create_index('ix_system_events_created_at', 'system_events', ['created_at'], unique=False)
    op.create_index('ix_system_events_event_type', 'system_events', ['event_type'], unique=False)
    op.create_index('ix_system_events_job_id', 'system_events', ['job_id'], unique=False)
    op.create_index('ix_system_events_request_id', 'system_events', ['request_id'], unique=False)
    op.create_index('ix_system_events_severity', 'system_events', ['severity'], unique=False)
    op.create_index('ix_system_events_severity_created_at', 'system_events', ['severity', 'created_at'], unique=False)
    op.create_index('ix_system_events_trace_id', 'system_events', ['trace_id'], unique=False)
    op.create_table('worker_heartbeats',
    sa.Column('worker_name', sa.String(), nullable=False),
    sa.Column('queue_name', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('current_job_id', sa.String(), nullable=True),
    sa.Column('metadata_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_worker_heartbeats')),
    sa.UniqueConstraint('worker_name', name=op.f('uq_worker_heartbeats_worker_name'))
    )
    op.create_index('ix_worker_heartbeats_last_seen_at', 'worker_heartbeats', ['last_seen_at'], unique=False)
    op.create_index('ix_worker_heartbeats_queue_name', 'worker_heartbeats', ['queue_name'], unique=False)
    op.create_index('ix_worker_heartbeats_status', 'worker_heartbeats', ['status'], unique=False)
    op.create_table('benchmark_queries',
    sa.Column('dataset_id', sa.UUID(), nullable=False),
    sa.Column('external_id', sa.String(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('split', sa.String(), nullable=True),
    sa.Column('metadata_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['dataset_id'], ['datasets.id'], name=op.f('fk_benchmark_queries_dataset_id_datasets')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_benchmark_queries')),
    sa.UniqueConstraint('dataset_id', 'external_id', name=op.f('uq_benchmark_queries_dataset_id'))
    )
    op.create_index('ix_benchmark_queries_dataset_id', 'benchmark_queries', ['dataset_id'], unique=False)
    op.create_index('ix_benchmark_queries_split', 'benchmark_queries', ['split'], unique=False)
    op.create_table('documents',
    sa.Column('dataset_id', sa.UUID(), nullable=False),
    sa.Column('external_id', sa.String(), nullable=False),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('source_url', sa.String(), nullable=True),
    sa.Column('metadata_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['dataset_id'], ['datasets.id'], name=op.f('fk_documents_dataset_id_datasets')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_documents')),
    sa.UniqueConstraint('dataset_id', 'external_id', name=op.f('uq_documents_dataset_id'))
    )
    op.create_index('ix_documents_dataset_id', 'documents', ['dataset_id'], unique=False)
    op.create_index('ix_documents_external_id', 'documents', ['external_id'], unique=False)
    op.create_table('index_versions',
    sa.Column('dataset_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('lexical_index_name', sa.String(), nullable=True),
    sa.Column('vector_collection_name', sa.String(), nullable=True),
    sa.Column('embedding_model', sa.String(), nullable=True),
    sa.Column('embedding_dimension', sa.Integer(), nullable=True),
    sa.Column('chunking_strategy', sa.String(), nullable=True),
    sa.Column('chunking_version', sa.String(), nullable=True),
    sa.Column('document_count', sa.Integer(), nullable=False),
    sa.Column('chunk_count', sa.Integer(), nullable=False),
    sa.Column('vector_count', sa.Integer(), nullable=False),
    sa.Column('config_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('activated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['dataset_id'], ['datasets.id'], name=op.f('fk_index_versions_dataset_id_datasets')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_index_versions')),
    sa.UniqueConstraint('dataset_id', 'name', name=op.f('uq_index_versions_dataset_id'))
    )
    op.create_index('ix_index_versions_dataset_id', 'index_versions', ['dataset_id'], unique=False)
    op.create_index('ix_index_versions_is_active', 'index_versions', ['is_active'], unique=False)
    op.create_index('ix_index_versions_status', 'index_versions', ['status'], unique=False)
    op.create_index('uq_index_versions_active_dataset', 'index_versions', ['dataset_id'], unique=True, postgresql_where=sa.text('is_active = true'))
    op.create_table('ingestion_runs',
    sa.Column('dataset_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('documents_loaded', sa.Integer(), nullable=False),
    sa.Column('chunks_created', sa.Integer(), nullable=False),
    sa.Column('queries_loaded', sa.Integer(), nullable=False),
    sa.Column('qrels_loaded', sa.Integer(), nullable=False),
    sa.Column('errors_count', sa.Integer(), nullable=False),
    sa.Column('config_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['dataset_id'], ['datasets.id'], name=op.f('fk_ingestion_runs_dataset_id_datasets')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ingestion_runs'))
    )
    op.create_index('ix_ingestion_runs_dataset_id', 'ingestion_runs', ['dataset_id'], unique=False)
    op.create_index('ix_ingestion_runs_started_at', 'ingestion_runs', ['started_at'], unique=False)
    op.create_index('ix_ingestion_runs_status', 'ingestion_runs', ['status'], unique=False)
    op.create_table('saved_queries',
    sa.Column('dataset_id', sa.UUID(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('metadata_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['dataset_id'], ['datasets.id'], name=op.f('fk_saved_queries_dataset_id_datasets')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_saved_queries'))
    )
    op.create_index('ix_saved_queries_created_at', 'saved_queries', ['created_at'], unique=False)
    op.create_index('ix_saved_queries_dataset_id', 'saved_queries', ['dataset_id'], unique=False)
    op.create_index('ix_saved_queries_source', 'saved_queries', ['source'], unique=False)
    op.create_table('chunks',
    sa.Column('dataset_id', sa.UUID(), nullable=False),
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('external_id', sa.String(), nullable=True),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('token_count', sa.Integer(), nullable=True),
    sa.Column('char_start', sa.Integer(), nullable=True),
    sa.Column('char_end', sa.Integer(), nullable=True),
    sa.Column('content_hash', sa.String(), nullable=False),
    sa.Column('chunking_strategy', sa.String(), nullable=False),
    sa.Column('chunking_version', sa.String(), nullable=False),
    sa.Column('metadata_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['dataset_id'], ['datasets.id'], name=op.f('fk_chunks_dataset_id_datasets')),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], name=op.f('fk_chunks_document_id_documents')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_chunks')),
    sa.UniqueConstraint('document_id', 'chunk_index', 'chunking_strategy', 'chunking_version', name=op.f('uq_chunks_document_id'))
    )
    op.create_index('ix_chunks_chunking_strategy_chunking_version', 'chunks', ['chunking_strategy', 'chunking_version'], unique=False)
    op.create_index('ix_chunks_content_hash', 'chunks', ['content_hash'], unique=False)
    op.create_index('ix_chunks_dataset_id', 'chunks', ['dataset_id'], unique=False)
    op.create_index('ix_chunks_document_id', 'chunks', ['document_id'], unique=False)
    op.create_table('evaluation_runs',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('dataset_id', sa.UUID(), nullable=False),
    sa.Column('index_version_id', sa.UUID(), nullable=True),
    sa.Column('experiment_config_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('query_count', sa.Integer(), nullable=False),
    sa.Column('failed_query_count', sa.Integer(), nullable=False),
    sa.Column('recall_at_5', sa.Float(), nullable=True),
    sa.Column('recall_at_10', sa.Float(), nullable=True),
    sa.Column('mrr_at_10', sa.Float(), nullable=True),
    sa.Column('ndcg_at_10', sa.Float(), nullable=True),
    sa.Column('p50_latency_ms', sa.Float(), nullable=True),
    sa.Column('p95_latency_ms', sa.Float(), nullable=True),
    sa.Column('avg_latency_ms', sa.Float(), nullable=True),
    sa.Column('config_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('report_path', sa.String(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['dataset_id'], ['datasets.id'], name=op.f('fk_evaluation_runs_dataset_id_datasets')),
    sa.ForeignKeyConstraint(['experiment_config_id'], ['experiment_configs.id'], name=op.f('fk_evaluation_runs_experiment_config_id_experiment_configs')),
    sa.ForeignKeyConstraint(['index_version_id'], ['index_versions.id'], name=op.f('fk_evaluation_runs_index_version_id_index_versions')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_evaluation_runs'))
    )
    op.create_index('ix_evaluation_runs_created_at', 'evaluation_runs', ['created_at'], unique=False)
    op.create_index('ix_evaluation_runs_dataset_id', 'evaluation_runs', ['dataset_id'], unique=False)
    op.create_index('ix_evaluation_runs_experiment_config_id', 'evaluation_runs', ['experiment_config_id'], unique=False)
    op.create_index('ix_evaluation_runs_index_version_id', 'evaluation_runs', ['index_version_id'], unique=False)
    op.create_index('ix_evaluation_runs_started_at', 'evaluation_runs', ['started_at'], unique=False)
    op.create_index('ix_evaluation_runs_status', 'evaluation_runs', ['status'], unique=False)
    op.create_table('index_jobs',
    sa.Column('index_version_id', sa.UUID(), nullable=False),
    sa.Column('job_id', sa.String(), nullable=True),
    sa.Column('job_type', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('chunks_total', sa.Integer(), nullable=False),
    sa.Column('chunks_completed', sa.Integer(), nullable=False),
    sa.Column('chunks_failed', sa.Integer(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('config_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['index_version_id'], ['index_versions.id'], name=op.f('fk_index_jobs_index_version_id_index_versions')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_index_jobs'))
    )
    op.create_index('ix_index_jobs_index_version_id', 'index_jobs', ['index_version_id'], unique=False)
    op.create_index('ix_index_jobs_job_id', 'index_jobs', ['job_id'], unique=False)
    op.create_index('ix_index_jobs_job_type', 'index_jobs', ['job_type'], unique=False)
    op.create_index('ix_index_jobs_started_at', 'index_jobs', ['started_at'], unique=False)
    op.create_index('ix_index_jobs_status', 'index_jobs', ['status'], unique=False)
    op.create_table('queries',
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('retrieval_mode', sa.String(), nullable=False),
    sa.Column('index_version_id', sa.UUID(), nullable=True),
    sa.Column('request_id', sa.String(), nullable=True),
    sa.Column('total_latency_ms', sa.Float(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('metadata_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['index_version_id'], ['index_versions.id'], name=op.f('fk_queries_index_version_id_index_versions')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_queries'))
    )
    op.create_index('ix_queries_created_at', 'queries', ['created_at'], unique=False)
    op.create_index('ix_queries_index_version_id', 'queries', ['index_version_id'], unique=False)
    op.create_index('ix_queries_request_id', 'queries', ['request_id'], unique=False)
    op.create_index('ix_queries_retrieval_mode', 'queries', ['retrieval_mode'], unique=False)
    op.create_index('ix_queries_status', 'queries', ['status'], unique=False)
    op.create_table('relevance_judgments',
    sa.Column('dataset_id', sa.UUID(), nullable=False),
    sa.Column('query_id', sa.UUID(), nullable=False),
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('query_external_id', sa.String(), nullable=False),
    sa.Column('document_external_id', sa.String(), nullable=False),
    sa.Column('relevance_score', sa.Float(), nullable=False),
    sa.Column('metadata_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['dataset_id'], ['datasets.id'], name=op.f('fk_relevance_judgments_dataset_id_datasets')),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], name=op.f('fk_relevance_judgments_document_id_documents')),
    sa.ForeignKeyConstraint(['query_id'], ['benchmark_queries.id'], name=op.f('fk_relevance_judgments_query_id_benchmark_queries')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_relevance_judgments')),
    sa.UniqueConstraint('query_id', 'document_id', name=op.f('uq_relevance_judgments_query_id'))
    )
    op.create_index('ix_relevance_judgments_dataset_id', 'relevance_judgments', ['dataset_id'], unique=False)
    op.create_index('ix_relevance_judgments_document_external_id', 'relevance_judgments', ['document_external_id'], unique=False)
    op.create_index('ix_relevance_judgments_query_external_id', 'relevance_judgments', ['query_external_id'], unique=False)
    op.create_table('evaluation_reports',
    sa.Column('evaluation_run_id', sa.UUID(), nullable=False),
    sa.Column('report_format', sa.String(), nullable=False),
    sa.Column('report_path', sa.String(), nullable=True),
    sa.Column('summary_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['evaluation_run_id'], ['evaluation_runs.id'], name=op.f('fk_evaluation_reports_evaluation_run_id_evaluation_runs')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_evaluation_reports'))
    )
    op.create_index('ix_evaluation_reports_created_at', 'evaluation_reports', ['created_at'], unique=False)
    op.create_index('ix_evaluation_reports_evaluation_run_id', 'evaluation_reports', ['evaluation_run_id'], unique=False)
    op.create_index('ix_evaluation_reports_report_format', 'evaluation_reports', ['report_format'], unique=False)
    op.create_table('query_traces',
    sa.Column('query_id', sa.UUID(), nullable=False),
    sa.Column('trace_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['query_id'], ['queries.id'], name=op.f('fk_query_traces_query_id_queries')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_query_traces')),
    sa.UniqueConstraint('query_id', name=op.f('uq_query_traces_query_id'))
    )
    op.create_index('ix_query_traces_created_at', 'query_traces', ['created_at'], unique=False)
    op.create_table('evaluation_query_results',
    sa.Column('evaluation_run_id', sa.UUID(), nullable=False),
    sa.Column('benchmark_query_id', sa.UUID(), nullable=True),
    sa.Column('query_external_id', sa.String(), nullable=False),
    sa.Column('query_text', sa.Text(), nullable=False),
    sa.Column('relevant_document_ids_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('retrieved_document_ids_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('recall_at_5', sa.Float(), nullable=True),
    sa.Column('recall_at_10', sa.Float(), nullable=True),
    sa.Column('mrr_at_10', sa.Float(), nullable=True),
    sa.Column('ndcg_at_10', sa.Float(), nullable=True),
    sa.Column('latency_ms', sa.Float(), nullable=True),
    sa.Column('trace_id', sa.UUID(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['benchmark_query_id'], ['benchmark_queries.id'], name=op.f('fk_evaluation_query_results_benchmark_query_id_benchmark_queries')),
    sa.ForeignKeyConstraint(['evaluation_run_id'], ['evaluation_runs.id'], name=op.f('fk_evaluation_query_results_evaluation_run_id_evaluation_runs')),
    sa.ForeignKeyConstraint(['trace_id'], ['query_traces.id'], name=op.f('fk_evaluation_query_results_trace_id_query_traces')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_evaluation_query_results')),
    sa.UniqueConstraint('evaluation_run_id', 'query_external_id', name=op.f('uq_evaluation_query_results_evaluation_run_id'))
    )
    op.create_index('ix_evaluation_query_results_benchmark_query_id', 'evaluation_query_results', ['benchmark_query_id'], unique=False)
    op.create_index('ix_evaluation_query_results_evaluation_run_id', 'evaluation_query_results', ['evaluation_run_id'], unique=False)
    op.create_index('ix_evaluation_query_results_trace_id', 'evaluation_query_results', ['trace_id'], unique=False)
    op.create_table('query_replays',
    sa.Column('saved_query_id', sa.UUID(), nullable=True),
    sa.Column('original_query_id', sa.UUID(), nullable=True),
    sa.Column('source_trace_id', sa.UUID(), nullable=True),
    sa.Column('target_trace_id', sa.UUID(), nullable=True),
    sa.Column('experiment_config_id', sa.UUID(), nullable=True),
    sa.Column('index_version_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('comparison_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['experiment_config_id'], ['experiment_configs.id'], name=op.f('fk_query_replays_experiment_config_id_experiment_configs')),
    sa.ForeignKeyConstraint(['index_version_id'], ['index_versions.id'], name=op.f('fk_query_replays_index_version_id_index_versions')),
    sa.ForeignKeyConstraint(['original_query_id'], ['queries.id'], name=op.f('fk_query_replays_original_query_id_queries')),
    sa.ForeignKeyConstraint(['saved_query_id'], ['saved_queries.id'], name=op.f('fk_query_replays_saved_query_id_saved_queries')),
    sa.ForeignKeyConstraint(['source_trace_id'], ['query_traces.id'], name=op.f('fk_query_replays_source_trace_id_query_traces')),
    sa.ForeignKeyConstraint(['target_trace_id'], ['query_traces.id'], name=op.f('fk_query_replays_target_trace_id_query_traces')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_query_replays'))
    )
    op.create_index('ix_query_replays_experiment_config_id', 'query_replays', ['experiment_config_id'], unique=False)
    op.create_index('ix_query_replays_index_version_id', 'query_replays', ['index_version_id'], unique=False)
    op.create_index('ix_query_replays_original_query_id', 'query_replays', ['original_query_id'], unique=False)
    op.create_index('ix_query_replays_saved_query_id', 'query_replays', ['saved_query_id'], unique=False)
    op.create_index('ix_query_replays_started_at', 'query_replays', ['started_at'], unique=False)
    op.create_index('ix_query_replays_status', 'query_replays', ['status'], unique=False)
    op.create_table('retrieval_candidates',
    sa.Column('query_id', sa.UUID(), nullable=False),
    sa.Column('trace_id', sa.UUID(), nullable=True),
    sa.Column('chunk_id', sa.UUID(), nullable=True),
    sa.Column('document_id', sa.UUID(), nullable=True),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('bm25_rank', sa.Integer(), nullable=True),
    sa.Column('dense_rank', sa.Integer(), nullable=True),
    sa.Column('fusion_rank', sa.Integer(), nullable=True),
    sa.Column('rerank_rank', sa.Integer(), nullable=True),
    sa.Column('final_rank', sa.Integer(), nullable=True),
    sa.Column('bm25_score', sa.Float(), nullable=True),
    sa.Column('dense_score', sa.Float(), nullable=True),
    sa.Column('fusion_score', sa.Float(), nullable=True),
    sa.Column('reranker_score', sa.Float(), nullable=True),
    sa.Column('latency_ms', sa.Float(), nullable=True),
    sa.Column('metadata_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['chunk_id'], ['chunks.id'], name=op.f('fk_retrieval_candidates_chunk_id_chunks')),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], name=op.f('fk_retrieval_candidates_document_id_documents')),
    sa.ForeignKeyConstraint(['query_id'], ['queries.id'], name=op.f('fk_retrieval_candidates_query_id_queries')),
    sa.ForeignKeyConstraint(['trace_id'], ['query_traces.id'], name=op.f('fk_retrieval_candidates_trace_id_query_traces')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_retrieval_candidates'))
    )
    op.create_index('ix_retrieval_candidates_chunk_id', 'retrieval_candidates', ['chunk_id'], unique=False)
    op.create_index('ix_retrieval_candidates_document_id', 'retrieval_candidates', ['document_id'], unique=False)
    op.create_index('ix_retrieval_candidates_final_rank', 'retrieval_candidates', ['final_rank'], unique=False)
    op.create_index('ix_retrieval_candidates_query_id', 'retrieval_candidates', ['query_id'], unique=False)
    op.create_index('ix_retrieval_candidates_source', 'retrieval_candidates', ['source'], unique=False)
    op.create_index('ix_retrieval_candidates_trace_id', 'retrieval_candidates', ['trace_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_retrieval_candidates_trace_id', table_name='retrieval_candidates')
    op.drop_index('ix_retrieval_candidates_source', table_name='retrieval_candidates')
    op.drop_index('ix_retrieval_candidates_query_id', table_name='retrieval_candidates')
    op.drop_index('ix_retrieval_candidates_final_rank', table_name='retrieval_candidates')
    op.drop_index('ix_retrieval_candidates_document_id', table_name='retrieval_candidates')
    op.drop_index('ix_retrieval_candidates_chunk_id', table_name='retrieval_candidates')
    op.drop_table('retrieval_candidates')
    op.drop_index('ix_query_replays_status', table_name='query_replays')
    op.drop_index('ix_query_replays_started_at', table_name='query_replays')
    op.drop_index('ix_query_replays_saved_query_id', table_name='query_replays')
    op.drop_index('ix_query_replays_original_query_id', table_name='query_replays')
    op.drop_index('ix_query_replays_index_version_id', table_name='query_replays')
    op.drop_index('ix_query_replays_experiment_config_id', table_name='query_replays')
    op.drop_table('query_replays')
    op.drop_index('ix_evaluation_query_results_trace_id', table_name='evaluation_query_results')
    op.drop_index('ix_evaluation_query_results_evaluation_run_id', table_name='evaluation_query_results')
    op.drop_index('ix_evaluation_query_results_benchmark_query_id', table_name='evaluation_query_results')
    op.drop_table('evaluation_query_results')
    op.drop_index('ix_query_traces_created_at', table_name='query_traces')
    op.drop_table('query_traces')
    op.drop_index('ix_evaluation_reports_report_format', table_name='evaluation_reports')
    op.drop_index('ix_evaluation_reports_evaluation_run_id', table_name='evaluation_reports')
    op.drop_index('ix_evaluation_reports_created_at', table_name='evaluation_reports')
    op.drop_table('evaluation_reports')
    op.drop_index('ix_relevance_judgments_query_external_id', table_name='relevance_judgments')
    op.drop_index('ix_relevance_judgments_document_external_id', table_name='relevance_judgments')
    op.drop_index('ix_relevance_judgments_dataset_id', table_name='relevance_judgments')
    op.drop_table('relevance_judgments')
    op.drop_index('ix_queries_status', table_name='queries')
    op.drop_index('ix_queries_retrieval_mode', table_name='queries')
    op.drop_index('ix_queries_request_id', table_name='queries')
    op.drop_index('ix_queries_index_version_id', table_name='queries')
    op.drop_index('ix_queries_created_at', table_name='queries')
    op.drop_table('queries')
    op.drop_index('ix_index_jobs_status', table_name='index_jobs')
    op.drop_index('ix_index_jobs_started_at', table_name='index_jobs')
    op.drop_index('ix_index_jobs_job_type', table_name='index_jobs')
    op.drop_index('ix_index_jobs_job_id', table_name='index_jobs')
    op.drop_index('ix_index_jobs_index_version_id', table_name='index_jobs')
    op.drop_table('index_jobs')
    op.drop_index('ix_evaluation_runs_status', table_name='evaluation_runs')
    op.drop_index('ix_evaluation_runs_started_at', table_name='evaluation_runs')
    op.drop_index('ix_evaluation_runs_index_version_id', table_name='evaluation_runs')
    op.drop_index('ix_evaluation_runs_experiment_config_id', table_name='evaluation_runs')
    op.drop_index('ix_evaluation_runs_dataset_id', table_name='evaluation_runs')
    op.drop_index('ix_evaluation_runs_created_at', table_name='evaluation_runs')
    op.drop_table('evaluation_runs')
    op.drop_index('ix_chunks_document_id', table_name='chunks')
    op.drop_index('ix_chunks_dataset_id', table_name='chunks')
    op.drop_index('ix_chunks_content_hash', table_name='chunks')
    op.drop_index('ix_chunks_chunking_strategy_chunking_version', table_name='chunks')
    op.drop_table('chunks')
    op.drop_index('ix_saved_queries_source', table_name='saved_queries')
    op.drop_index('ix_saved_queries_dataset_id', table_name='saved_queries')
    op.drop_index('ix_saved_queries_created_at', table_name='saved_queries')
    op.drop_table('saved_queries')
    op.drop_index('ix_ingestion_runs_status', table_name='ingestion_runs')
    op.drop_index('ix_ingestion_runs_started_at', table_name='ingestion_runs')
    op.drop_index('ix_ingestion_runs_dataset_id', table_name='ingestion_runs')
    op.drop_table('ingestion_runs')
    op.drop_index('uq_index_versions_active_dataset', table_name='index_versions', postgresql_where=sa.text('is_active = true'))
    op.drop_index('ix_index_versions_status', table_name='index_versions')
    op.drop_index('ix_index_versions_is_active', table_name='index_versions')
    op.drop_index('ix_index_versions_dataset_id', table_name='index_versions')
    op.drop_table('index_versions')
    op.drop_index('ix_documents_external_id', table_name='documents')
    op.drop_index('ix_documents_dataset_id', table_name='documents')
    op.drop_table('documents')
    op.drop_index('ix_benchmark_queries_split', table_name='benchmark_queries')
    op.drop_index('ix_benchmark_queries_dataset_id', table_name='benchmark_queries')
    op.drop_table('benchmark_queries')
    op.drop_index('ix_worker_heartbeats_status', table_name='worker_heartbeats')
    op.drop_index('ix_worker_heartbeats_queue_name', table_name='worker_heartbeats')
    op.drop_index('ix_worker_heartbeats_last_seen_at', table_name='worker_heartbeats')
    op.drop_table('worker_heartbeats')
    op.drop_index('ix_system_events_trace_id', table_name='system_events')
    op.drop_index('ix_system_events_severity_created_at', table_name='system_events')
    op.drop_index('ix_system_events_severity', table_name='system_events')
    op.drop_index('ix_system_events_request_id', table_name='system_events')
    op.drop_index('ix_system_events_job_id', table_name='system_events')
    op.drop_index('ix_system_events_event_type', table_name='system_events')
    op.drop_index('ix_system_events_created_at', table_name='system_events')
    op.drop_table('system_events')
    op.drop_index('ix_experiment_configs_retrieval_mode', table_name='experiment_configs')
    op.drop_index('ix_experiment_configs_is_default', table_name='experiment_configs')
    op.drop_table('experiment_configs')
    op.drop_index('ix_datasets_source', table_name='datasets')
    op.drop_index('ix_datasets_name', table_name='datasets')
    op.drop_table('datasets')
    # ### end Alembic commands ###
