import { isSnapshotMode } from "@/lib/demo-mode";

export function DemoModeBanner() {
  if (!isSnapshotMode()) {
    return null;
  }

  return (
    <div className="border-b border-cyan-900/60 bg-cyan-950/30 px-4 py-3 text-sm text-cyan-100 md:px-6">
      <div className="mx-auto flex max-w-7xl flex-col gap-1">
        <div className="font-semibold">Public demo mode</div>
        <div className="max-w-5xl leading-6 text-cyan-100/85">
          This hosted demo uses real precomputed outputs generated by the full Aletheia local pipeline. Live retrieval,
          index rebuilds, and admin jobs are disabled publicly to avoid always-on search and ML infrastructure costs.
        </div>
        <div className="text-xs text-cyan-200/70">
          The full live stack runs locally with FastAPI, Postgres, Redis/RQ, OpenSearch, Qdrant, embeddings, and reranking.
        </div>
      </div>
    </div>
  );
}
